version: '3.7'

services:
  app:
    image: nginx:1.16.1
    ports:
      - "8081:80"
    volumes:
      - ./dev/docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - magento-web
  phpfpm:
    build:
      context: ./dev/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - magento-web
  mysql:
    image: mysql:5.7
    volumes:
      - ./dev/docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./dev/docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: aaaaaa
      MYSQL_ROOT_PASSWORD: aaaaaa
    ports:
      - 3307:3306
    networks:
      - magento-web
  es01:
    image: elasticsearch:7.17.5
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - magento-web

volumes:
  data01:
    driver: local
networks:
  magento-web:
    driver: bridge
